### ISSUE TITLE
How are unpublish events handled?

### ISSUE THREAD

**Issue by zeke** [dickeyxxx/elephant#10]
This happened today: https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.37j7cvuek

If I was using elephant as my registry, would those unpublished modules stick around, or would they be unpublished just like they are on the registry.npmjs.org ?

**Comment by dickeyxxx** [comment]
you won't be able to install them since they won't be included in the manifest, but the tarballs will still be in S3

**Comment by dickeyxxx** [comment]
well, that's if a version was unpublished, if the entire package disappeared it would still be in elephant

**Comment by tmaher** [comment]
Continuing in that vein, what happens if the package disappears and then reappears?

**Comment by tmaher** [comment]
Err, reappears because someone squatted on the name

**Comment by dickeyxxx** [comment]
if the tarball sha changes it'll be redownloaded

**Comment by dickeyxxx** [comment]
I don't think generally you can republish the same version again though. It happened once with pad-left, but I think that was a one-time special case.

**Comment by nmccready** [comment]
> you won't be able to install them since they won't be included in the manifest, but the tarballs will still be in S3

Is there a way to ignore this? The whole purpose of elephant is to have a fail safe back up of repos regardless of what happened on npm. Could a setting be added to ignore unpublishing?

**Comment by dickeyxxx** [comment]
That's not the goal of elephant, the goal is to stay up when npmjs.com is down but npmjs.com is STILL the canonical source of truth. If npmjs.com is up and has a different package metadata it should continue to use that.

Having said that, an unpublished package would still be available since elephant considers a 404 down.

**Comment by dickeyxxx** [comment]
given npm's policy has changed around this, I'm going to close this. But If there is anything specific you would like to see definitely let me know!
