### ISSUE TITLE
Alternative for env variables

### ISSUE THREAD

**Issue by ealves-pt** [dickeyxxx/elephant#12]
Is it possible to add an alternative to environment variables? I want to build a docker container with this project but the idea of passing environment variables is not very safe.

**Comment by dickeyxxx** [comment]
Not very safe? Compared to what?

**Comment by ealves-pt** [comment]
I should have been more specific, the only environment variable that concerns me is the AWS secret key.

According to docker security standards one should not pass secret keys as environment variables because those are available to all the other containers and that could lead to security problems.

**Comment by dickeyxxx** [comment]
can you point me to some documentation that describes this? and an alternative?

This is a 12 factor app, which is configured solely by environment variables. If there is a safer alternative that works better with docker though I can look into it.

**Comment by ealves-pt** [comment]
You can read something about this here: https://github.com/docker/docker/issues/13490. There is no clear better way on how to handle this so tbh I don't which is the best solution.

I would say that the option could be to fetch those values from a file if they are not set that way I could keep those private and limit access to them.

**Comment by dickeyxxx** [comment]
Given that, I'm not inclined to offer another solution. Static files are not a good way to configure an app and goes against 12 factor.

**Comment by dickeyxxx** [comment]
if you really want to use a file, just use the `--env-file` argument

**Comment by dickeyxxx** [comment]
or if you want to do it only within the container, you could use this https://www.npmjs.com/package/dotenv

**Comment by ealves-pt** [comment]
I understand but I also think that this should not be so deeply attached to the 12 factor methodology and should give more flexibility. The idea of having secret keys in env variables is definitely not a good practice because they are shared between linked containers.

Anyway, thank you very much for the feedback.
