### ISSUE TITLE
REDIS_URL seems to be required, but docs have it 'optional'

### ISSUE THREAD

**Issue by HenryTheHamster** [dickeyxxx/elephant#14]
Hey, great tool, we've been wanting something like this for _ages_

Just an issue we had setting up, the docs mention REDIS_URL as being optional, but we experienced timeouts unless we had a running cluster and this env var set. Is there something we're missing, or is this just a docs bug?

Cheers, Andy

**Comment by dickeyxxx** [comment]
fixed in https://github.com/dickeyxxx/elephant/commit/a45a6481813f2f744727c9d9cdee55f90a626fb1
