### ISSUE TITLE
Scoped dependencies from official npm registry not working

### ISSUE THREAD

**Issue by therippa** [dickeyxxx/elephant#16]
Take this node module for instance - https://github.com/request/core/blob/master/package.json

It references scoped packages (@request) available on npmregistry.org, but not published to the elephant repository.

When requesting them, it seems the tarball isn't created.

**Comment by dickeyxxx** [comment]
what exactly isn't working? I'm able to install that package through an elephant server.

**Comment by therippa** [comment]
My bad, was the end of a long day and didn't realize it was still pointed to our older build of elephant.
