### ISSUE TITLE
htpasswd not a command

### ISSUE THREAD

**Issue by steveostudios** [dickeyxxx/elephant#2]
I've deployed this to heroku, but I'm confused about the htpasswd authentication. When I do 
```
./bin/get-htpasswd > ./htpasswd
htpasswd -nB steve >> ./htpasswd
```
I get `htpasswd: command not found`. I'm positive that it is me doing something wrong. Any help would be greatly appreciated!

**Comment by dickeyxxx** [comment]
it's this tool https://httpd.apache.org/docs/2.4/programs/htpasswd.html
it's not part of this package
